# Generated by Django 3.2.9 on 2021-11-17 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0003_auto_20211118_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='asd',
        ),
        migrations.AddField(
            model_name='task',
            name='Name',
            field=models.CharField(max_length=200, null=True, verbose_name='NameAuthor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
