# Generated by Django 3.2.9 on 2021-11-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_alter_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.example'),
        ),
    ]
