# Generated by Django 3.2.9 on 2021-11-22 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0008_alter_task_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Name',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='NameAuthor'),
        ),
        migrations.AlterField(
            model_name='example',
            name='Name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='NameKey'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='au', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ex', to='testApp.example'),
        ),
    ]
