# Generated by Django 3.2.9 on 2021-11-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0009_auto_20211122_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NameAuthor'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('genre', models.CharField(max_length=1, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('postal_code_4', models.PositiveIntegerField(null=True)),
                ('postal_code_3', models.PositiveIntegerField(null=True)),
                ('marital_status', models.CharField(max_length=1, null=True)),
                ('child_amount', models.PositiveSmallIntegerField(null=True)),
                ('is_merchant', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
