# Generated by Django 3.2.9 on 2021-11-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Пол'),
        ),
    ]
