# Generated by Django 3.2.9 on 2021-11-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0022_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Name',
        ),
    ]
