# Generated by Django 3.2.9 on 2021-11-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0037_auto_20211128_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/testApp/jpg', verbose_name='Картинка'),
        ),
    ]
