# Generated by Django 3.2.9 on 2021-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0052_auto_20211130_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tg',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vk',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Вконтакте'),
        ),
    ]
