# Generated by Django 3.2.9 on 2021-11-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0054_auto_20211130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of Cash Payment', null=True, verbose_name='Дата рождения'),
        ),
    ]
