# Generated by Django 3.2.9 on 2021-12-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0060_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
