# Generated by Django 3.2.9 on 2021-12-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0065_auto_20211207_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Room',
        ),
    ]
