# Generated by Django 3.2.9 on 2021-12-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0066_remove_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes', to='testApp.room'),
        ),
    ]
