# Generated by Django 3.2.9 on 2021-12-08 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0067_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mes', to=settings.AUTH_USER_MODEL),
        ),
    ]
