# Generated by Django 3.2.9 on 2021-12-08 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0068_alter_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Room',
        ),
    ]
