# Generated by Django 3.2.9 on 2021-12-09 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0070_room_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='author',
        ),
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ManyToManyField(null=True, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
