# Generated by Django 3.2.9 on 2021-12-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0077_alter_room_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='person',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
