# Generated by Django 3.2.9 on 2021-12-13 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0080_alter_room_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
