# Generated by Django 3.2.9 on 2021-12-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0082_alter_room_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Введите мыло:'),
        ),
    ]
