# Generated by Django 3.2.9 on 2021-12-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0083_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(max_length=99, null=True, verbose_name='Возраст'),
        ),
    ]
