# Generated by Django 3.2.9 on 2021-12-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0084_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(max_length=2, null=True, verbose_name='Возраст'),
        ),
    ]
