# Generated by Django 3.2.9 on 2021-12-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0093_auto_20211216_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='second_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
