# Generated by Django 3.2.9 on 2021-12-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0094_alter_userprofile_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
